#!/bin/bash

# Rev 1: Initial release (2015-01-04)
# Rev 2: Fix line continuation operators, add a few allowed constants (2015-01-05)
# Rev 3: Improve indent auto-detection, add 3 to the allowed magic number list. (2015-01-17)
# Rev 4: Allow spaces in paths (2015-02-03)
# Rev 5: Allow whitespace after method name in definition; allow lack of whitespace after if, for, and other keywords generally followed by an open paren. Add rev note in output. (2015-02-12)
# Rev 6: Allow a lack of whitespace before a braced block of statements. (2015-02-13)
# Rev 7: Allow javadoc with multiple linebreaks without an accompanying <p> tag. (2015-02-16)
# Rev 8: Remove need for braces for single-line if/for/while/etc. (2015-02-18)
# Rev 9: Require @throws tags for explicitly thrown exceptions. (2015-03-04)
# Rev 10: Now properly requires @throws tags for explicitly thrown exceptions. (2015-03-15)
# Rev 11: Allow @throws on unchecked runtime exceptions. (2015-03-25)
# Rev 12: Relaxed restrictions on the placement of right curly braces for if/loop constructs. (2015-10-01)
# Rev 13: Updated for automated grading with Jenkins (2017-12-15)
# Rev 14: Enclosed all variables with double-quotes to avoid broken paths (2020-01-12)
# Rev 15: Removed SimplifyBooleanReturn and re-indented
REV=15

# Detect the path where this script was called from -- this should be inside a checkstyle install directory.
CHECKSTYLE_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Path to the checkstyle configuration file to use.
CONFIG_FILE="$CHECKSTYLE_PATH/csc116_checks_jenkins.xml"

# Path to the "-all" jar file -- you shouldn't need to mess with this unless changing checkstyle versions.
CHECKSTYLE_JAR="$CHECKSTYLE_PATH/checkstyle-6.1.1-all.jar"

# The class to execute -- this shouldn't change
CHECKSTYLE_CLASS=com.puppycrawl.tools.checkstyle.Main

if [ ! -f "$CHECKSTYLE_JAR" ]; then
  echo "ERROR: Unable to locate checkstyle jar file -- did you move this script from the checkstyle installation?"
  exit 1
fi

if [[ x$1 == x ]]; then
  echo "Checkstyle front-end script by Tyler Bletsch and CSC116 Teaching Staff."
  echo "  (Rev $REV)"
  echo ""
  echo "Run checkstyle on one or more files."
  echo ""
  echo "Syntax: $0 <files ...>"
  exit 1
fi

echo "** Doing style check..."
java -classpath "$CHECKSTYLE_JAR" "$CHECKSTYLE_CLASS" -c "$CONFIG_FILE" "$@"
#if [[ $? == 0 ]] ; then
#    echo ">> No errors, you're good :-)"
#else
#    echo ">> Style errors detected :-("
#fi
echo
